#!/usr/bin/env perl

use strict;
use warnings;
use Mojo::Redis2;
use Mojo::Log;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('PotNode');
